---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
        - name: parser
          image: <IMAGE-PARSER>
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: parser
spec:
  type: ClusterIP
  selector:
    app: parser
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
